[package]
name = "synq-compiler"
version = "0.1.0"
edition = "2021"

[features]
default = ["native"]
native = [
    "dep:synq-pqc-shims",
    "synq-pqc-shims/native",
    "dep:pqcrypto",
    "quantumvm/native",
]
wasm = [
    "dep:synq-pqc-shims",
    "synq-pqc-shims/wasm",
]

[dependencies]
aivm = { path = "../aivm" }
serde       = { workspace = true }
serde_json  = { workspace = true }
hex         = { workspace = true }
pest        = "2.7.7"
pest_derive = "2.7.7"
sha3        = "0.10"
ruint       = { workspace = true }

quantumvm      = { package = "synq-vm",        path = "../vm", default-features = false }
synq-pqc-shims = { package = "synq-pqc-shims", path = "../pqc-shims", default-features = false, optional = true }
pqcrypto       = { workspace = true, optional = true }

[dev-dependencies]
assert_matches = "1.5.0"
